version: '3.5'
services:
  service-announcement:
    image: migsking/dms-sms-service-announcement:${VERSION}
    container_name: service-announcement
    networks:
      - dms-sms-local
    environment:
      - DB_PASSWORD=${DB_PASSWORD}
      - CONSUL_ADDR=${CONSUL_ADDRESS}
      - JAEGER_AGENT_HOST=${JAEGER_HOST}
      - JAEGER_AGENT_PORT=${JAEGER_PORT}

networks:
  dms-sms-local:
    name: dms-sms-local
    driver: bridge