name: docker-deploy

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:     
  DOCKER_BUILD_AND_DEPLOY:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          submodules: true
          
      - name: gradle build
        run: ./gradlew build
        
      - name: build docker image
        run: docker build -t migsking/dms-sms-service-announcement .

      - name: publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: migsking/dms-sms-service-announcement
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
